### PR TITLE
Multi threading for sauth

### PR DESCRIPTION
**Pull request by elfgoh**
This PR enhances `sauth` to uses threads for handling requests

### CODE REVIEW

**Comment by Granitosaurus** [comment]
Sorry for late reply; let me take a look at this :)

**Comment by keiranmraine** [comment]
Would be really nice to see this merged, possibly with the messages via logging.

**Comment by Incubatio** [comment]
up

**Comment by Granitosaurus** [comment]
merged, rebased and released in `1.1.0`. You can enable with with `--thread` flag:
```shell
$ sauth someuser somepass 127.0.0.1 1234 --thread
Serving "/home/dex/projects/sauth" directory on http://127.0.0.1:1234 using threading
```

**Pull request merged**
